[project]
name = "test-task-4"
version = "0.1.0"
description = ""
authors = [
    {name = "dmitrii",email = "mathmtit@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django (>=5.2.4,<6.0.0)",
    "stripe (>=12.3.0,<13.0.0)",
    "python-decouple (>=3.8,<4.0)",
    "whitenoise (>=6.9.0,<7.0.0)",
    "gunicorn (>=23.0.0,<24.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
