# Generated by Django 5.2.4 on 2025-07-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_discount_tax_remove_order_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='type',
        ),
        migrations.AddField(
            model_name='discount',
            name='code',
            field=models.CharField(default='NO_DISCOUNT', max_length=50, unique=True),
        ),
    ]
