# Generated by Django 5.2.4 on 2025-07-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_remove_discount_type_discount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(default='usd', max_length=4),
        ),
    ]
